args <- commandArgs(TRUE) 
fileName <- args[1] 
diabetes_data<-read.csv(fileName,header = FALSE)  
paste("The correlation between attribute1 and the class variable is: ",cor(diabetes_data$V1,diabetes_data$V9),sep="")
paste("The correlation between attribute2 and the class variable is: ",cor(diabetes_data$V2,diabetes_data$V9),sep="")
paste("The correlation between attribute3 and the class variable is: ",cor(diabetes_data$V3,diabetes_data$V9),sep="")
paste("The correlation between attribute4 and the class variable is: ",cor(diabetes_data$V4,diabetes_data$V9),sep="") 
paste("The correlation between attribute5 and the class variable is: ",cor(diabetes_data$V5,diabetes_data$V9),sep="")
paste("The correlation between attribute6 and the class variable is: ",cor(diabetes_data$V6,diabetes_data$V9),sep="")
paste("The correlation between attribute7 and the class variable is: ",cor(diabetes_data$V7,diabetes_data$V9),sep="")
paste("The correlation between attribute8 and the class variable is: ",cor(diabetes_data$V8,diabetes_data$V9),sep="")
